addr: 127.0.0.1
port: :51242
rafts:
  me: 2
  endpoints:
    - addr: 127.0.0.1
      port: :32300
    - addr: 127.0.0.1
      port: :32301
    - addr: 127.0.0.1
      port: :32302
databasepath: "data2"
maxraftstate: 100000
