addr: 127.0.0.1
port: :51241
rafts:
  me: 1
  endpoints:
    - addr: 127.0.0.1
      port: :32300
    - addr: 127.0.0.1
      port: :32301
    - addr: 127.0.0.1
      port: :32302
databasepath: "data1"
maxraftstate: 100000
