clerk:
  etcdaddrs:
    - localhost:51240
    - localhost:51241
    - localhost:51242
addr: 127.0.0.1
baseUrl: "/firEtcd"
port: :51030

# TLS配置（可选）
tls:
  certFile: "certs/gateway.crt"
  keyFile: "certs/gateway.key"
  caFile: "certs/ca.crt"
  clientAuth: true
  minVersion: "1.2"
  maxVersion: "1.3"
  insecureSkipVerify: false
